export default {
  REC_COUNTRIES: 'REC_COUNTRIES',
  CHANGE_INDEX: 'CHANGE_INDEX',
  CHANGE_ITEM: 'CHANGE_ITEM',
  TOGGLE_VISIBLE: 'TOGGLE_VISIBLE',
  REC_LENGTH: 'REC_LENGTH',
  REC_MATCHES: 'REC_MATCHES'
};
